Repository CS2103-AY1819S1-W13-1/main, pull requests merged in 2018-11, with the labels that each got.

#112 Change the title of the app from Address App to InsuRen.
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: type.task

#120 Add author tag
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.task

#123 Add reposense config file
  _reposense/config.json
Labels: type.task

#143 Fix layout formatting when a long name is input
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#142 Fix bug where meeting get removed
  src/main/java/seedu/address/logic/commands/PictureCommand.java
Labels: type.Bug

#146 Remove dummy webpage
  .travis.yml
  build.gradle
  docs/DummySearchPage.html
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: severity.Low

#147 Make date validation stricter
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
Labels: priority.High, type.Bug

#154 Small grammatical fixes in documentation
  docs/UserGuide.adoc
Labels: type.task

#156 Remove irrelevant parts of the DeveloperGuide.
  docs/DeveloperGuide.adoc
Labels: type.task

#160 Update diagrams to reflect InsuRen
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
Labels: type.task

#149 V1.4 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ByNameCommandClassDiagram.pptx
  docs/diagrams/ByNameCommandSequenceDiagram.pptx
  docs/images/ByNameCommandClassDiagram.png
  docs/images/ByNameCommandSequenceDiagram.png
  docs/team/louizkimchan.adoc
  docs/team/zioul123.adoc
Labels: type.task

#181 Change the "do not use edit or delete" in tags to a recommendation.
  docs/UserGuide.adoc
Labels: priority.High
