Repository CS2103-AY1819S1-W13-1/main, pull requests merged in 2018-10, with the labels that each got.

#16 Profiles v1.1 - Make phone, email and address to be optional fields.
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, type.Enhancement

#15 AboutUs.doc: Add responsibilities, change product name, fix images.
  docs/AboutUs.adoc
  docs/images/A19Sean.png
  docs/images/AyushChatto.png
  docs/images/chantca95.png
  docs/images/denzelchung.png
  docs/images/zioul123.png
Labels: type.task

#18 In Progress: Create meeting class
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.Medium, status.Ongoing, type.Story

#22 Picture Command
  src/main/java/seedu/address/logic/commands/PictureCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PictureCommandParser.java
  src/main/resources/images/placeholder_image.jpg
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/PictureCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PictureCommandParserTest.java
Labels: priority.High, status.Ongoing, type.Story

#39 V1.2: Add functionality to edit person by name.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditByNameCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsAllKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EditByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, type.Enhancement

#40 v1.2: Able to set contact photo from images folder
  src/main/java/seedu/address/logic/commands/PictureCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PictureCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Picture.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PictureCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PictureTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High, type.Enhancement

#45 v1.2 Incorporate meeting list
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/storage/XmlAdaptedMeeting.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High, type.Enhancement

#56 V1.2 General documentation changes
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: type.task

#71 Tag delete feature stop failing tests
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.task

#78 Remove names from typical persons lists to make tests pass.
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#76 V1.3 - EditByNameCommand System Tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.task

#80 v1.3 - EditByName changes
  src/main/java/seedu/address/logic/commands/EditByNameCommand.java
Labels: type.Enhancement

#82 Updated Picture Path for PictureCommand
  src/main/java/seedu/address/logic/commands/PictureCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Picture.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PictureCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PictureCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PictureTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Bug

#79 V1.3 - Add the DeleteByNameCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/IndexParserUtil.java
  src/main/java/seedu/address/logic/PersonFinderUtil.java
  src/main/java/seedu/address/logic/commands/DeleteByNameCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditByNameCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/IndexParserUtilTest.java
  src/test/java/seedu/address/logic/PersonFinderUtilTest.java
  src/test/java/seedu/address/logic/commands/DeleteByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/EditByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: priority.Medium, type.Enhancement, type.Story

#87 Fixed bug with spaces in path
  src/main/java/seedu/address/model/person/Picture.java
Labels: type.Bug

#86 Check for meeting prefix
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
Labels: priority.Medium, type.Bug

#85 v1.3 Search by meeting
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/MeetingsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MeetingsCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/SameMeetingDayPredicate.java
  src/test/java/seedu/address/logic/commands/MeetingsCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement

#103 Edits according to ta
  docs/DeveloperGuide.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
Labels: priority.Medium, type.task

#102 Tag feature documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/TagCommand1StateDiagram.png
  docs/images/TagCommand2StateDiagram.png
  docs/images/TagCommand3StateDiagram.png
  docs/images/TagCommand4StateDiagram.png
  docs/images/TagCommand5StateDiagram.png
  docs/images/TagCommand6StateDiagram.png
  docs/images/TagCommandActivityDiagram.png
Labels: priority.High, type.task
